import Head from 'next/head'
import Header from '../components/Header'
import MovieSection from '../components/MovieSection'
import Navigation from '../components/Navigation'
import requests from '../utils/requests'


export default function Home({results}) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* Header (links and HULU logo) */}

      <Header />

      {/* Navigation (genres etc) */}

      <Navigation />

      {/* Content - movies */}

      <MovieSection results={results} />
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => res.json());

  return {
    props: {
      results: request.results,
    }
  }
}
